name: Deploy-release

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: npm ci
        run: npm ci
      - name: Create .env file
        run: echo "${{ secrets.ENV_PROD }}" > .env
      - name: Create releases.json file
        run: curl https://api.github.com/repos/lapi-hotel-group/furport-front/releases > src/releases.json
      - name: npm run build
        run: npm run build
      - name: npm run build docs
        run: npm run build && cp -r build/ ../build/docs/
        working-directory: ./docs
      - name: ssh key generate
        run: echo "$SSH_PRIVATE_KEY" > key && chmod 600 key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: rsync Deploy
        run: rsync -rlptgoD --delete --exclude ".git/" -e "ssh -i key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p ${SSH_PORT}" build/ $SSH_USER@$SSH_HOST:$DEPLOY_PATH
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
